import { Metadata } from 'next';
import {useTranslations} from 'next-intl';

export const metadata: Metadata = {
  title: 'SalesWal | Home',
  description: 'Generated by create next app',
};
 
export default function Index() {
  const t = useTranslations('Index');
  return <h1>{t('title')}</h1>;
}