import BoxReveal from "@/components/magicui/BoxReveal";
import { Metadata } from "next";
import { useTranslations } from "next-intl";

export const metadata: Metadata = {
  title: "SalesWal | Home",
  description: "Generated by create next app",
};

export default function Index() {
  const title = useTranslations("Landing.title");
  const text = useTranslations("Landing");
  return (
    <>
      <div className="grid sm:grid-cols-1 xl:grid-cols-2 gap-16">
        <div>
          <div>
            <div className="flex flex-wrap gap-2 sm:text-7xl font-extrabold text-5xl ">
              <h1 className="mr-4">{title("first")}</h1>
              <BoxReveal boxColor={"#297bff"} duration={0.5}>
                <p className="text-my-blue ">{title("second")}</p>
              </BoxReveal>
            </div>
            <div className="flex flex-col gap-2 text-5xl sm:text-7xl font-extrabold mt-2">
              <h1>{title("third")}</h1>
              <BoxReveal boxColor={"#297bff"} duration={0.5}>
                <p className="text-my-blue">{title("fourth")}</p>
              </BoxReveal>
            </div>
            <p className="mt-5 font-medium text-base sm:text-lg text-justify">{text("subtitle")}</p>
            <button className="bg-my-blue text-white font-medium py-2 px-4 mt-5 hover:bg-white hover:text-my-blue hover:underline duration-300 transition-all">{text("button")}</button>         
          </div>
        </div>
        <div className="bg-black h-80 w-full"></div>
      </div>
    </>
  );
}
